import streamlit as st
import geopandas as gpd
import folium
from streamlit_folium import st_folium

# 1. Page Configuration
st.set_page_config(page_title="Bishkek School Resilience", layout="wide")

# 2. Optimized Data Loading
@st.cache_data
def load_data():
    all_schools = gpd.read_file("data/all_schools.geojson")
    priority_schools = gpd.read_file("data/priority_schools.geojson")
    proposed_nodes = gpd.read_file("data/proposed_nodes.geojson")
    return all_schools, priority_schools, proposed_nodes

all_schools, priority_schools, proposed_nodes = load_data()

# --- SIDEBAR NAVIGATION ---
st.sidebar.title("🧭 Navigation")
page = st.sidebar.radio("Go to:", ["Project Dashboard", "Mission & Context", "Technical Workflow"])

# --- PAGE 1: PROJECT DASHBOARD ---
if page == "Project Dashboard":
    st.title("🇰🇬 Bishkek Infrastructure Resilience")
    st.write("Visualizing connectivity gaps and optimizing school infrastructure.")

    # METRICS SECTION
    st.subheader("Project Impact")
    col1, col2, col3 = st.columns(3)
    
    avg_reduction = 1.42 
    col1.metric("High-Risk Schools", len(priority_schools), "Targeted")
    col2.metric("Optimal Tower Nodes", len(proposed_nodes), "Proposed")
    col3.metric("Avg. Distance Saved", f"{avg_reduction} km", "Per School")

    st.divider()

    # INTERACTIVE MAP
    st.subheader("Infrastructure Optimization Map")
    m = folium.Map(location=[42.8747, 74.5698], zoom_start=12, tiles="CartoDB positron")

    for _, row in all_schools.iterrows():
        point = row.geometry.centroid 
        folium.CircleMarker(
            location=[point.y, point.x],
            radius=2, color="gray", fill=True, alpha=0.4
        ).add_to(m)

    for _, row in priority_schools.iterrows():
        point = row.geometry.centroid
        folium.Marker(
            location=[point.y, point.x],
            popup=f"Priority School",
            icon=folium.Icon(color="red", icon="info-sign")
        ).add_to(m)

    for _, row in proposed_nodes.iterrows():
        folium.Marker(
            location=[row.geometry.y, row.geometry.x],
            popup="<b>Proposed Resilience Node</b>",
            icon=folium.Icon(color="cadetblue", icon="tower", prefix="fa")
        ).add_to(m)

    st_folium(m, width=1200, height=600)

# --- PAGE 2: MISSION & CONTEXT ---
elif page == "Mission & Context":
    st.title("Project Mission")
    
    st.markdown("""
    ### Bridging the Digital Divide in Bishkek
    In a rapidly urbanizing city, educational infrastructure often lags behind residential growth. Many schools in peripheral districts suffer from **Digital Isolation**—they are too far from existing cellular towers to support modern digital learning.

    This project uses spatial data science to identify the most isolated schools and propose the 4 most mathematically efficient locations for new "Resilience Nodes."
    
    ---
    ### Key Terminology
    
    * **Priority Schools:** Schools identified with a high **Connectivity Fragility Index (CFI)**. These are facilities currently located more than **2km** from the nearest high-capacity cellular infrastructure.
    * **Proposed Resilience Node:** A mathematically optimized location generated by the **K-Means Clustering** algorithm. It represents the "geographical center" of a cluster of high-risk schools, ensuring a single tower provides the maximum benefit.
    """)
    
    st.info("Goal: Scaling this model can help NGOs and city officials prioritize humanitarian tech spending.")

# --- PAGE 3: TECHNICAL WORKFLOW ---
elif page == "Technical Workflow":
    st.title("Methodology & Steps")
    
    st.write("How this project went from raw data to actionable infrastructure coordinates:")

    with st.expander("Step 1: Data Sourcing"):
        st.write("Extracted 180+ school locations and existing cellular infrastructure across Bishkek using **OpenStreetMap (OSM)** via the OSMnx library.")
        
    with st.expander("Step 2: Spatial Auditing"):
        st.write("Performed a proximity analysis using **GeoPandas** to measure the precise distance from every school to the nearest tower in UTM meters.")
        
    with st.expander("Step 3: Risk Modeling"):
        st.write("Developed a **CFI Scoring** system to rank schools. 16 schools were flagged as 'High Risk' due to extreme distance from the grid.")
        
    with st.expander("Step 4: Machine Learning (Optimization)"):
        st.write("Applied **K-Means Clustering** to the 16 priority schools to find the optimal coordinates ($x, y$) for 4 new infrastructure nodes.")

    st.success("The final result is a data-driven proposal for city infrastructure planning.")